language: android
jdk: oraclejdk11

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.3
    - android-30
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
before_script:
  - chmod +x gradlew
script:
  - ./gradlew build

after_success:
  - ./gradlew generateJavadoc

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  edge: true
  keep_history: true
  local_dir: dynamic-support/build/docs/javadoc/release
  on:
    branch: master
    tags: true
